twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        idleTimeout: '%idle_timeout%'
    form_themes:
        - '@HillrangeForm/FormTheme/bootstrap.html.twig'
    paths:
        '%kernel.project_dir%/templates/bundles/hillrangesecurity/': 'HillrangeSecurity'
